name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  BINARY_DIR: build
  INSTALL_DIR: install

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout project and recurse submodules.
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: CMake configure.
        run: >-
          cmake -B ${{ env.BINARY_DIR }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }}

      - name: CMake build release.
        run: cmake --build ${{ env.BINARY_DIR }} --config ${{ env.BUILD_TYPE }} --target install

      - name: Upload install.
        uses: actions/upload-artifact@v3
        with:
          name: Install-${{ env.BUILD_TYPE }}-${{ runner.os }}
          retention-days: 7
          path: |
            ${{ env.INSTALL_DIR }}/

      - name: Upload build logs.
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Logs-${{ env.BUILD_TYPE }}-${{ runner.os }}
          retention-days: 14
          path: |
            ${{ env.BINARY_DIR }}/**/CMakeCache.txt
            ${{ env.BINARY_DIR }}/**/CMakeOutput.log
            ${{ env.BINARY_DIR }}/**/CMakeError.log
